apiVersion: v1
kind: Service
metadata:
  name: hrnodepordservice-srv  
spec: 
  type: NodePort
  selector:
    app: hrservice
  ports:
    - name: hrservice
      protocol: TCP
      port: 80
      targetPort: 80